### PR TITLE
Use vertical addressing for a ten-fold speed increase

### PR DESCRIPTION
**Pull request by anescient**
I changed the _initialize functions to put the 1306 in Vertical Addressing Mode and updated the image-loading function to match. This way the image data can be transformed as needed using PIL, and individual pixels don't need to be handled by this module.

This is much, much more efficient.
Benchmarks using a 128x64 display over SPI with a generation 1 RPi Model B,
loading a full-frame image and displaying it:
Old way: 16 frames per second, uses 100% CPU
This way: 135 frames per second, uses 80% CPU
So now the serial link is a bottleneck, as it should be.
Upping the SPI clock to 40MHz:
Old way: 16 frames per second, uses 100% CPU
This way: 154 frames per second, uses 90% CPU

128x64 + gen 1 Model B + SPI is the only configuration I've tested.
There's no good reason I2C should break, but it's probably much slower than SPI.
I've updated the classes for 128x32 and 96x16, but I do not have either available to test.
My main portability concern would be PIL's 1-bit image format; this method relies on the one-bit-per-pixel raw format and bit ordering that my setup uses.

### CODE REVIEW

**Comment by drakkhen** [comment]
Oh, nice!  Haven't tried this yet but I'm very excited to as soon as I get a chance.  The current module seems to make my pi become unresponsive after several days of updating the display.  Maybe this would help?  We'll see...

**Comment by anescient** [comment]
If I treat my 128x64 as a 128x32, the result is broken in the same way, new method or old method. So 128x32 is probably fine.

If I treat it as 96x16, the result is broken slightly differently, so it definitely needs testing with an actual 96x16. I've added a 96x16 happycat image.

**Comment by anescient** [comment]
I'm less concerned about PIL portability now that I know some more about it. Turns out it's actually using one-_byte_-per-pixel to store a 2-color image, and it translates it to one-_bit_-per-pixel when you call tobytes(). In other words tobytes() probably behaves the same everywhere.

**Comment by thedjinn** [comment]
I tested this on the 128x32 PiOLED (via I2C on a Raspberry Pi Zero W) and it works great! Went from 15 to 70 FPS in my application with CPU from 100% to 50%.

**Comment by ladyada** [comment]
hiya thanks for the PR, this library is being deprecated - we have a similar library that works with Python3 and modern linux computers. please check out this guide for more info
https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring

we refactored all our displays to use a `framebuf` object so that all monochrome/eink displays can recycle the same code. testing with a pi4, a 128x32 oled with PIL image + framebuf show is 125 FPS. On a Pi zero its 45 FPS (use 1MHz i2c!)

if you have optimizations please PR them to https://github.com/adafruit/Adafruit_CircuitPython_framebuf - but we dont want to have display-specific address hacks. so ideally it would just be some way to improve the PIL pixel thruput.
for now, these displays are small, and portability is most important for us :)

**Pull request closed without merging**
